name: HTML Validator

on: [push]

jobs:
  html-validator:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate HTML
      run: |
        # install HTML validator
        npm install -g html-validator
        
        # run validator on all .html files in repository
        html-validator **/*.html
        